#!/bin/bash

set -e
readonly RELEASE_DIR="_release"

main() {
  make_release_dir
  local name="beer-me-$(git describe --always --dirty --tags)"
  go build -o "$RELEASE_DIR/$name"
  (cd $RELEASE_DIR && openssl sha256 -out "$name-SHA256SUM" "$name")
}

make_release_dir() {
  rm -rf "$RELEASE_DIR"
  mkdir -p "$RELEASE_DIR"
}

main "$@"
